command line params, no boto, nicer output

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,27 +1,32 @@
 #!/bin/bash
 #http://stackoverflow.com/a/11301911/1705163
 
-PYVERSION=2.7.7
-VEVERSION=1.11.6
+usage() {
+  SCRIPT_NAME=$(basename "${BASH_SOURCE[0]}")
+  echo "Usage: $SCRIPT_NAME -d <dir> -p <python version> -v <virtualenv version> -f"
+  echo "  f to force download even if <dir> already exists"
+  echo "Example: $SCRIPT_NAME -d ve -p 2.7.7 -v 1.11.6 -f"
+  exit 1
+}
 
-DEST=$(pwd)
-echo "current directory: $DEST"
-if [ -n "$1" ]; then
-    #realpath does not require the dir to exist
-    if hash realpath 2>/dev/null; then
-        echo "using realpath"
-        DEST=$(realpath -s "$1")
-    else
-        if [ "${1:0:1}" == "/" ]; then
-            echo "absolute path"
-            DEST=$1
-        else
-            echo "relative path"
-            DEST=$PWD/$1
-        fi
-    fi
+while getopts ":d:p:v:fh" opt; do
+  case $opt in
+    h) usage ;;
+    d) DIR=$OPTARG ;;
+    p) PYVERSION=$OPTARG ;;
+    v) VEVERSION=$OPTARG ;;
+    f) FORCE=1 ;;
+    :) echo "Option -$OPTARG requires an argument." >&2 ;;
+    \?) echo "Invalid option: -$OPTARG" >&2 ;;
+  esac
+done
+
+if [[ -z "$DIR" || -z "$PYVERSION" || -z "$VEVERSION" ]]; then
+  usage
 fi
-echo "absolute destination path: $DEST"
+
+
+DEST=$(readlink -f $DIR)
 
 #setup python
 install_python() {
@@ -32,10 +37,12 @@ install_python() {
     if [[ -d $SRCDIR  && -d $INSTALLDIR ]]; then
         cd $SRCDIR
         local TARBALL=Python-$PYVERSION.tgz
-        curl -O https://www.python.org/ftp/python/$PYVERSION/$TARBALL
+        echo "downloading $TARBALL..."
+        curl --silent -O https://www.python.org/ftp/python/$PYVERSION/$TARBALL
         tar -zxvf $TARBALL > /dev/null 2>&1
         cd Python-$PYVERSION
         ./configure --prefix=$INSTALLDIR > /dev/null 2>&1
+        echo "building Python-$PYVERSION..."
         make > /dev/null 2>&1
         make install > /dev/null 2>&1
         PYTHON=$INSTALLDIR/bin/python
@@ -56,30 +63,32 @@ install_virtualenv() {
         tar -zxvf $TARBALL > /dev/null 2>&1
         cd virtualenv-$VEVERSION
         if [ -z "$PYTHON" ]; then
-            echo "no python: $PYTHON"
+            echo "no python: $PYTHON" >&2
         else
             $PYTHON virtualenv.py $INSTALLDIR -p $PYTHON
-            #activate so that any python / pip runs in this python
+            #create a more convenient / findable activate link
             ACTIVATE=$DEST/activate
-            ln -s $INSTALLDIR/bin/activate $ACTIVATE
-            source $ACTIVATE
-            echo $ACTIVATE
+            ln -sf $INSTALLDIR/bin/activate $ACTIVATE
         fi
     fi
     popd
 }
 
+echo "absolute destination path: $DEST"
+if [[ $FORCE && -d $DEST ]]; then
+  echo "forcing install: removing $DEST"
+  rm -rf $DEST
+fi
+
+if [ -d $DEST ]; then
+  echo "skipping install: $DEST exists"
+  exit 1
+fi
+
 #run the installation
-echo "Installing Python..."
+echo "Installing Python $PYVERSION..."
 install_python
-echo "Installing Virtualenv..."
+echo "Installing Virtualenv $VEVERSION..."
 install_virtualenv
-echo "installing boto..."
-pip install boto
-
-python -c "
-import boto
-print(boto.Version)
-"
-
-deactivate
+echo done
+exit 0
